### 20240412003114 ###

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 50
    schedule:
      interval: "daily"

  # Maintain dependencies for Python 
  - package-ecosystem: "pip"
    directory: /
    open-pull-requests-limit: 50
    schedule:
      interval: "daily"
    #groups:
    #  python:
    #    patterns:
    #      - "*"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: /greynoise
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"      
      
  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: /openbbterminal
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      
  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: /pingcastle
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
  
  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: /pstcli
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
  
  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: /sles
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: /steamcmd
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      
